#!/usr/bin/env bash
# debugging nginx port 80
# Get active IPv4 IPs
IP_LIST=$(ip -4 addr show | grep inet | awk '{print $2}')

# Edit Nginx configuration
CONF_FILE=/etc/nginx/nginx.conf
sudo cp $CONF_FILE ${CONF_FILE}.bak  # create a backup of the original configuration
sudo sed -i '/http {/a\
'"$IP_LIST"'' $CONF_FILE

# Test and restart Nginx
sudo nginx -t && sudo service nginx restart

