#!/usr/bin/env bash
# debugging nginx port 80
# Edit Nginx configuration
# Test and restart Nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -t && sudo service nginx restart

